version: '2'

services:
  ip-echo:
    restart: always
    image: peppersec/ip-echo
    environment:
      # VIRTUAL_HOST: ip.tornado.cash
      # LETSENCRYPT_HOST: ip.tornado.cash
      # VIRTUAL_PORT: 3000
      VIRTUAL_HOST: ip.tornado.cash
      LETSENCRYPT_HOST: ip.tornado.cash

networks:
  default:
    external:
      name: frontend_default